mkdir -p APP/data/Bam/Mapped/{BamGATK,BamFreebayes}
mkdir -p APP/data/chromosome
mkdir -p APP/data/Datafastq/{Fastqc,KDSD,ResQC,unmapped}
mkdir -p APP/data/intercep
mkdir -p APP/data/Reference
mkdir -p APP/data/Sam
mkdir -p APP/data/freebayesfile/{Filterring/mergefile,mergevcffile,metrics,txtfile,vcffile}
mkdir -p APP/data/variants.bcftools/{Filterring/{MatriceSNPS,filteredType,MATRICE,mergefile},mergevcffile,metrics}
mkdir -p APP/data/gatkfile/{Filterring/{MATRICE,MatriceSNPS,mergefile},metrics,recal,mergevcfile,vcffile,textfile}
mkdir -p APP/data/Annoted/{AnnotatedFILEbyFILE/singlefilerepport,report}