mkdir -p APP/data/Bam/Mapped
mkdir -p APP/data/Datafastq/Fastqc
mkdir -p APP/data/Datafastq/KDSD
mkdir -p APP/data/Datafastq/ResQC
mkdir -p APP/data/Datafastq/unmapped
mkdir -p APP/data/intercep
mkdir -p APP/data/Reference
mkdir -p APP/data/Sam
mkdir -p APP/data/variants.bcftools/Filterring/MATRICE
mkdir -p APP/data/variants.bcftools/Filterring/MatriceSNPS
mkdir -p APP/data/variants.varscan/Filterring/MATRICE
mkdir -p APP/data/variants.varscan/Filterring/MatriceSNPS
