mkdir -p APP/data/Bam/Mapped/BamGATK
mkdir -p APP/data/Datafastq/Fastqc
mkdir -p APP/data/Datafastq/KDSD
mkdir -p APP/data/Datafastq/ResQC
mkdir -p APP/data/Datafastq/unmapped
mkdir -p APP/data/intercep
mkdir -p APP/data/Reference
mkdir -p APP/data/Sam
mkdir -p APP/data/variants.bcftools/Filterring/MATRICE
mkdir -p APP/data/variants.bcftools/Filterring/MatriceSNPS
mkdir -p APP/data/variants.bcftools/Filterring/filteredType
mkdir -p APP/data/gatkfile/{Filterring/MATRICE,metrics,recal,vcffile}
mkdir -p APP/data/Annoted/AnnotatedFILEbyFILE/singlefilerepport
mkdir -p APP/data/Annoted/report