#!/bin/sh

rm -rf APP/data/Bam/Mapped/*.bai
rm -rf APP/data/Bam/Mapped/*.bam
rm -rf APP/data/Bam/*.bam
rm -rf APP/data/Datafastq/Fastqc/*.zip
rm -rf APP/data/Datafastq/Fastqc/*.html
rm -rf APP/data/Datafastq/KDSD/*
rm -rf APP/data/Datafastq/ResQC/*
rm -rf APP/data/Datafastq/unmapped/*.fastq
rm -rf APP/data/variants.bcftools/Filterring/*.vcf
rm -rf APP/data/variants.bcftools/*.vcf
rm -rf APP/data/variants.varscan/*.vcf
rm -rf APP/data/variants.bcftools/Filterring/MATRICE/*.tsv
rm -rf APP/data/variants.bcftools/Filterring/filteredType/*.vcf
rm -rf APP/data/variants.bcftools/Filterring/MatriceSNPS/*.tsv
rm -rf APP/data/variants.bcftools/Filterring/*.tsv
rm -rf APP/data/variants.bcftools/Filterring/*.gz
rm -rf APP/data/variants.bcftools/Filterring/*.tbi
rm -rf APP/data/variants.bcftools/Filterring/*.bed
rm -rf APP/data/Sam/*.sam
rm -rf APP/data/Datafastq/*.fastq
rm -rf APP/data/variants.varscan/*.mpileup
rm -rf APP/data/variants.varscan/Filterring/*.vcf
rm -rf APP/data/variants.varscan/Filterring/MATRICE/*
rm -rf APP/data/variants.varscan/Filterring/MatriceSNPS/*
rm -rf APP/data/intercep/*
rm -rf APP/data/variants.bcftools/Filterring/filteredType/*
rm -rf APP/data/gatkfile/Filterring/*.vcf*
rm -rf APP/data/gatkfile/recal/*.vcf*
rm -rf APP/data/gatkfile/vcffile/*.vcf*
rm -rf APP/data/gatkfile/metrics/*metrics.*
rm -rf APP/data/gatkfile/recal/*.table
rm -rf APP/data/Bam/Mapped/BamGATK/*.bam*
rm -rf APP/data/Bam/Mapped/BamGATK/*.bai*
rm -rf APP/data/gatkfile/Filterring/*vcf*
rm -rf APP/data/gatkfile/Filterring/*tsv*
rm -rf APP/data/gatkfile/Filterring/MATRICE/*.tsv
rm -rf APP/data/gatkfile/Filterring/MatriceSNPS/*.tsv
rm -rf APP/data/Annoted/AnnotatedFILEbyFILE/singlefilerepport/*.txt && rm -rf APP/data/Annoted/AnnotatedFILEbyFILE/singlefilerepport/*.html
rm -rf APP/data/Annoted/AnnotatedFILEbyFILE/singlefilerepport/*
rm -f APP/data/Annoted/AnnotatedFILEbyFILE/*.vcf
rm -f APP/data/Annoted/report/*
rm -f APP/data/Annoted/*