#!/bin/sh

rm -f APP/data/Bam/Mapped/*.bai
rm -f APP/data/Bam/Mapped/*.bam
rm -f APP/data/Bam/*.bam
rm -f APP/data/Datafastq/Fastqc/*.zip
rm -f APP/data/Datafastq/Fastqc/*.html
rm -f APP/data/Datafastq/KDSD/*
rm -f APP/data/Datafastq/ResQC/*
rm -f APP/data/Datafastq/*
rm -f APP/data/Datafastq/unmapped/*.fastq
rm -f APP/data/variants.bcftools/Filterring/*.vcf
rm -f APP/data/variants.bcftools/*.vcf
rm -f APP/data/variants.varscan/*.vcf
rm -f APP/data/variants.bcftools/Filterring/MATRICE/*.tsv
rm -f APP/data/variants.bcftools/Filterring/filteredType/*.vcf
rm -f APP/data/variants.bcftools/Filterring/MatriceSNPS/*.tsv
rm -f APP/data/variants.bcftools/Filterring/mergefile/*.vcf
rm -f APP/data/variants.bcftools/mergevcffile/*
rm -f APP/data/variants.bcftools/Filterring/*.tsv
rm -f APP/data/variants.bcftools/Filterring/*.gz
rm -f APP/data/variants.bcftools/Filterring/*.tbi
rm -f APP/data/variants.bcftools/Filterring/*.bed
rm -f APP/data/Sam/*.sam
rm -f APP/data/Datafastq/*.fastq
rm -f APP/data/variants.varscan/*.mpileup
rm -f APP/data/variants.varscan/Filterring/*.vcf
rm -f APP/data/variants.varscan/Filterring/MATRICE/*
rm -f APP/data/variants.varscan/Filterring/MatriceSNPS/*
rm -f APP/data/intercep/*
rm -f APP/data/variants.bcftools/Filterring/filteredType/*
rm -f APP/data/gatkfile/Filterring/*.vcf*
rm -f APP/data/gatkfile/recal/*.vcf*
rm -f APP/data/gatkfile/vcffile/*.vcf*
rm -f APP/data/gatkfile/metrics/*metrics.*
rm -f APP/data/gatkfile/recal/*.table
rm -f APP/data/Bam/Mapped/BamGATK/*.bam*
rm -f APP/data/Bam/Mapped/BamGATK/*.bai*
rm -f APP/data/gatkfile/Filterring/*vcf*
rm -f APP/data/gatkfile/Filterring/*tsv*
rm -f APP/data/gatkfile/Filterring/MATRICE/*.tsv
rm -f APP/data/gatkfile/Filterring/MatriceSNPS/*.tsv
rm -f APP/data/gatkfile/Filterring/mergefile/*
rm -f APP/data/gatkfile/mergevcfile/*.vcf
rm -f APP/data/Annoted/AnnotatedFILEbyFILE/singlefilerepport/*.txt && rm -f APP/data/Annoted/AnnotatedFILEbyFILE/singlefilerepport/*.html
rm -f APP/data/Annoted/AnnotatedFILEbyFILE/singlefilerepport/*
rm -f APP/data/Annoted/AnnotatedFILEbyFILE/*.vcf
rm -f APP/data/Annoted/report/*
rm -f APP/data/Annoted/*
rm -f APP/data/freebayesfile/Filterring/mergefile/*.vcf
rm -f APP/data/freebayesfile/mergevcffile/*.vcf
rm -f APP/data/freebayesfile/metrics/*.txt
rm -f APP/data/freebayesfile/vcffile/*.vcf
rm -f APP/data/freebayesfile/Filterring/*.vcf
rm -f APP/data/Bam/Mapped/BamFreebayes/*
rm -f APP/data/chromosome/*